pipeline {  
    agent none
    stages {
        stage('Build') {
            agent {
              docker {
                image 'python:2.7.16-slim'
                args '--user root'
              }
            }
            when{
              changeset "**/vote/**"
            }
            steps {
                echo 'Compiling vote app'
                dir('vote'){
                  sh 'pip install -r requirements.txt'
		            }
            }
        }
        stage('Test') {
            agent {
              docker {
                image 'python:2.7.16-slim'
                args '--user root'
              }
            }          
	          when{
              changeset "**/vote/**"
            }
            steps {
                echo 'Testing vote app'
                dir('vote'){
                  sh 'pip install -r requirements.txt'
                  sh 'nosetests -v'
		            }
            }
        }
        stage('Docker Package') {
            agent any
            when{
              changeset "**/vote/**"
              //branch "master"
            }
            steps {
                echo 'Creating docker image for vote app'
                dir('vote'){
                  script{
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-credentials') {
                      def dockerImage = docker.build("amouskite/vote:${env.BUILD_ID}")
                      dockerImage.push()
                      //dockerImage.push('master')
                    }
                  }
		            }
            }
        }
        
    }
}
