pipeline {
    agent {
      docker {
        image 'maven:3.6.1-alpine'
        args '-v $HOME/.m2:/root/.m2'
      }
    }

    stages {
        stage('Build') {
            when{
              changeset "**/worker/**"
            }
            steps {
                echo 'Compiling worker app'
                dir('worker'){
                  sh 'mvn compile'
		            }
            }
        }
        stage('Test') {
	          when{
              changeset "**/worker/**"
            }
            steps {
                echo 'Testing worker app'
                dir('worker'){
                  sh 'mvn clean test'
		            }
            }
        }
        stage('Package') {
            when{
              changeset "**/worker/**"
              branch "master"
            }
            steps {
                echo 'Packaging worker app'
                dir('worker'){
		              sh 'mvn package -DskipTests'
                  archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
		            }
            }
        }
        stage('Docker Package') {
            when{
              changeset "**/worker/**"
            }
            steps {
                echo 'Creating docker image for worker app'
                dir('worker'){
                  script{
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-credentials') {
                      def dockerImage = docker.build("worker:${env.BUILD_ID}")
                      dockerImage.push()
                    }
                  }
		            }
            }
        }

    }

}
